FROM ghcr.io/osgeo/gdal:ubuntu-small-3.7.2

ENV DEBIAN_FRONTEND=noninteractive \
    LC_ALL=C.UTF-8 \
    LANG=C.UTF-8 \
    TINI_VERSION=v0.19.0

ADD https://github.com/krallin/tini/releases/download/${TINI_VERSION}/tini /tini
RUN chmod +x /tini

RUN apt-get update \
    # Developer convenience
    && apt-get install -y \
        git \
        fish \
        wget \
        unzip \
        # Build tools\
        build-essential \
        python3-pip \
        python3-dev \
        # For Psycopg2
        libpq-dev\
        # Yaml parsing speedup, I think
        libyaml-dev \
        lsb-release \
        # for shapely with --no-binary
        libgeos-dev \
        postgresql-client-14 \
    # Cleanup
    && apt-get autoclean \
    && apt-get autoremove \
    && rm -rf /var/lib/{apt,dpkg,cache,log}

COPY requirements_odc.txt constraints.txt version.txt /conf/

RUN cat /conf/version.txt \
  && pip install --no-cache-dir --upgrade pip \
  && pip install --no-cache-dir \
    -r /conf/requirements_odc.txt \
    -c /conf/constraints.txt

RUN pip freeze

# Copy gparser
RUN git clone https://github.com/Open-EO/openeo-pg-parser-python.git
RUN cd openeo-pg-parser-python && pip install .

RUN git clone https://github.com/SARScripts/openeo_odc_driver.git

WORKDIR /

ENTRYPOINT ["/tini", "--"]

WORKDIR /openeo_odc_driver/openeo_odc_driver/

CMD ["gunicorn","-c","gunicorn.conf.py","odc_backend:app"]