---
services:
  # Start docker container for datacube-index
  index:
    image: opendatacube/datacube-index:latest
    environment:
      - DB_HOSTNAME=database-1.cluster-cfgam6cksth1.us-west-2.rds.amazonaws.com
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
      - DB_PORT=5432
      - AWS_DEFAULT_REGION=us-west-2
      - PRODUCT_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-products.csv
      - METADATA_CATALOG=https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml
    command: tail -f /dev/null

  # Start docker container for Explorer
  explorer:
    image: opendatacube/explorer:latest
    environment:
      - DB_HOSTNAME=database-1.cluster-cfgam6cksth1.us-west-2.rds.amazonaws.com
      - DB_USERNAME=postgres
      - DB_PASSWORD=opendatacubepassword
      - DB_DATABASE=postgres
    ports:
      - 9000:8080
    restart: always
