---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datacube-config
data:
  DB_HOSTNAME: 'database-1.cluster-cfgam6cksth1.us-west-2.rds.amazonaws.com'
  DB_USERNAME: 'postgres'
  DB_DATABASE: 'postgres'
  DB_PORT: '5432'
  AWS_DEFAULT_REGION: 'us-west-2'
  PRODUCT_CATALOG: 'https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-products.csv'
  METADATA_CATALOG: 'https://raw.githubusercontent.com/GeoscienceAustralia/dea-config/a4f39b485b33608a016032d9987251881fec4b6f/workspaces/sandbox-metadata.yaml'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacube-index
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacube-index
  template:
    metadata:
      labels:
        app: datacube-index
    spec:
      containers:
        - name: datacube-index
          image: opendatacube/datacube-index:local
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: datacube-config
            - secretRef:
                name: datacube-secret
          command: ['tail', -f", '/dev/null']
          restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datacube-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datacube-explorer
  template:
    metadata:
      labels:
        app: datacube-explorer
    spec:
      containers:
        - name: datacube-explorer
          image: opendatacube/explorer:local
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
          envFrom:
            - configMapRef:
                name: datacube-config
            - secretRef:
                name: datacube-secret
          ports:
            - containerPort: 8080
          restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: explorer-ingress
spec:
  rules:
    - host: explorer.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: explorer-service
                port:
                  number: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: explorer-service
spec:
  selector:
    app: datacube-explorer
  ports:
    - name: explorer
      port: 9000
      targetPort: 8080
  type: ClusterIP
# Add a secret to the k8s cluster for DB_PASSWORD
# kubectl create secret generic datacube-secret --from-literal=DB_PASSWORD=opendatacubepassword
